import cap from "./../../../assets/images/products/cap.jpg";
import hoodie from "./../../../assets/images/products/hoodie.jpg";
import turtle from "./../../../assets/images/products/turtle-neck.jpg";

// Unsplash images for additional products
const IMG = {
    sneakers:     "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    watch:        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
    backpack:     "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
    sunglasses:   "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&q=80",
    joggers:      "https://images.unsplash.com/photo-1594938298603-c8148c4b984d?w=400&q=80",
    denim_jacket: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400&q=80",
    polo_shirt:   "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400&q=80",
    wallet:       "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&q=80",
    belt:         "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400&q=80",
    scarf:        "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&q=80",
    bomber:       "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80",
    dress:        "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&q=80",
};

export const products = [
    {
        _id: "prod1",
        sku: "CAP-001",
        title: "Classic Logo Cap",
        description: "A timeless structured cap with an embroidered logo. Adjustable strap for a perfect fit.",
        short_description: "Structured cap with embroidered logo.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/cap", secure_url: cap },
        allow_back_orders: false,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 55 },
        regular_price: 55,
        sale_price: 45,
        on_sale: true,
        sale: { status: true, price: { currency: "GBP", amount: 45 }, start_date: "2024-01-01", end_date: "2024-12-31" },
        weight: "0.15",
        dimensions: { length: "20", width: "20", height: "10" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 52,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: [],
        attributes: [],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 1, name: "caps", slug: "caps" }],
        visibility: "visible",
        date_published: "2024-01-10",
        created_at: "2024-01-10T08:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod2",
        sku: "HOD-002",
        title: "Pullover Hoodie",
        description: "Comfortable midweight pullover hoodie in a relaxed fit. Kangaroo pocket and adjustable drawstring.",
        short_description: "Midweight pullover hoodie, relaxed fit.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/hoodie", secure_url: hoodie },
        allow_back_orders: false,
        low_stock_threshold: 3,
        sold_individually: false,
        price: { currency: "GBP", amount: 55 },
        regular_price: 65,
        sale_price: 55,
        on_sale: true,
        sale: { status: true, price: { currency: "GBP", amount: 55 }, start_date: "2024-03-01", end_date: "2024-06-30" },
        weight: "0.45",
        dimensions: { length: "35", width: "28", height: "5" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 5,
        stock_status: "lowstock",
        backorders: "no",
        reviews_allowed: true,
        upsells: ["prod1"],
        cross_sells: [],
        attributes: [
            { id: 1, name: "Colour", options: ["Black", "Navy", "Grey"], visible: true, variation: false },
            { id: 2, name: "Size", options: ["S", "M", "L", "XL"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 2, name: "hoodies", slug: "hoodies" }],
        visibility: "visible",
        date_published: "2024-03-01",
        created_at: "2024-03-01T09:00:00Z",
        featured: true,
        gallery: []
    },
    {
        _id: "prod3",
        sku: "TNK-003",
        title: "Ribbed Turtleneck Jumper",
        description: "Cosy ribbed-knit turtleneck jumper in a slim fit. Soft mid-weight fabric, perfect for layering.",
        short_description: "Slim-fit ribbed turtleneck knit jumper.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/turtle", secure_url: turtle },
        allow_back_orders: false,
        low_stock_threshold: 10,
        sold_individually: false,
        price: { currency: "GBP", amount: 150 },
        regular_price: 150,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 150 }, start_date: "", end_date: "" },
        weight: "0.20",
        dimensions: { length: "30", width: "25", height: "3" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 200,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod1", "prod2"],
        attributes: [
            { id: 2, name: "Size", options: ["XS", "S", "M", "L", "XL", "XXL"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 5, name: "knitwear", slug: "knitwear" }, { id: 6, name: "jumpers", slug: "jumpers" }],
        visibility: "visible",
        date_published: "2024-05-15",
        created_at: "2024-05-15T10:30:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod4",
        sku: "SNK-004",
        title: "Low-Top Canvas Sneakers",
        description: "Clean low-top canvas sneakers with a vulcanised rubber sole. Unisex silhouette, available in multiple colourways.",
        short_description: "Vulcanised low-top canvas sneakers.",
        type: "variable",
        status: "publish",
        variations: [],
        image: { public_id: "products/sneakers", secure_url: IMG.sneakers },
        allow_back_orders: false,
        low_stock_threshold: 8,
        sold_individually: false,
        price: { currency: "GBP", amount: 75 },
        regular_price: 75,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 75 }, start_date: "", end_date: "" },
        weight: "0.80",
        dimensions: { length: "32", width: "15", height: "12" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 88,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod1"],
        attributes: [
            { id: 3, name: "Colour", options: ["White", "Black", "Red", "Blue"], visible: true, variation: true },
            { id: 4, name: "UK Size", options: ["6", "7", "8", "9", "10", "11"], visible: true, variation: true }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 7, name: "Footwear", slug: "footwear" }],
        tags: [{ id: 7, name: "sneakers", slug: "sneakers" }, { id: 8, name: "casual", slug: "casual" }],
        visibility: "visible",
        date_published: "2024-06-01",
        created_at: "2024-06-01T10:00:00Z",
        featured: true,
        gallery: []
    },
    {
        _id: "prod5",
        sku: "WTC-005",
        title: "Minimalist Quartz Watch",
        description: "Slim quartz watch with a stainless-steel case and genuine leather strap. Water-resistant to 30m.",
        short_description: "Slim stainless-steel quartz watch, leather strap.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/watch", secure_url: IMG.watch },
        allow_back_orders: false,
        low_stock_threshold: 4,
        sold_individually: true,
        price: { currency: "GBP", amount: 129 },
        regular_price: 159,
        sale_price: 129,
        on_sale: true,
        sale: { status: true, price: { currency: "GBP", amount: 129 }, start_date: "2024-11-01", end_date: "2025-01-31" },
        weight: "0.12",
        dimensions: { length: "5", width: "4", height: "1" },
        shipping_class: "express",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 23,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod8"],
        attributes: [
            { id: 5, name: "Strap Colour", options: ["Tan", "Black", "Brown"], visible: true, variation: false }
        ],
        purchase_note: "Delivered in a gift-ready box.",
        enable_reviews: true,
        categories: [{ id: 8, name: "Accessories", slug: "accessories" }],
        tags: [{ id: 9, name: "watches", slug: "watches" }, { id: 10, name: "gifts", slug: "gifts" }],
        visibility: "visible",
        date_published: "2024-07-20",
        created_at: "2024-07-20T11:00:00Z",
        featured: true,
        gallery: []
    },
    {
        _id: "prod6",
        sku: "BKP-006",
        title: "Urban Daypack 20L",
        description: "Lightweight 20-litre daypack with a padded laptop sleeve (up to 15\"), front zip pocket and water-bottle side pockets.",
        short_description: "20L daypack with 15\" laptop sleeve.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/backpack", secure_url: IMG.backpack },
        allow_back_orders: false,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 49 },
        regular_price: 49,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 49 }, start_date: "", end_date: "" },
        weight: "0.60",
        dimensions: { length: "45", width: "30", height: "15" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 41,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod8", "prod9"],
        attributes: [
            { id: 6, name: "Colour", options: ["Black", "Olive", "Navy"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 8, name: "Accessories", slug: "accessories" }],
        tags: [{ id: 11, name: "bags", slug: "bags" }, { id: 12, name: "travel", slug: "travel" }],
        visibility: "visible",
        date_published: "2024-08-05",
        created_at: "2024-08-05T09:30:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod7",
        sku: "SGL-007",
        title: "Polarised Aviator Sunglasses",
        description: "Classic metal-frame aviators with UV400 polarised lenses. Spring hinges for a comfortable all-day fit.",
        short_description: "UV400 polarised metal-frame aviators.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/sunglasses", secure_url: IMG.sunglasses },
        allow_back_orders: false,
        low_stock_threshold: 6,
        sold_individually: false,
        price: { currency: "GBP", amount: 39 },
        regular_price: 55,
        sale_price: 39,
        on_sale: true,
        sale: { status: true, price: { currency: "GBP", amount: 39 }, start_date: "2025-03-01", end_date: "2025-06-30" },
        weight: "0.03",
        dimensions: { length: "15", width: "6", height: "4" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 0,
        stock_status: "outofstock",
        backorders: "notify",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod5"],
        attributes: [
            { id: 7, name: "Lens", options: ["Gold / Brown", "Silver / Grey", "Black / Smoke"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 8, name: "Accessories", slug: "accessories" }],
        tags: [{ id: 13, name: "sunglasses", slug: "sunglasses" }, { id: 8, name: "casual", slug: "casual" }],
        visibility: "visible",
        date_published: "2024-09-10",
        created_at: "2024-09-10T08:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod8",
        sku: "JOG-008",
        title: "Tapered Jogger Trousers",
        description: "Soft French-terry joggers with a tapered leg, elasticated waistband and side zip pockets.",
        short_description: "Tapered French-terry joggers with zip pockets.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/joggers", secure_url: IMG.joggers },
        allow_back_orders: false,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 45 },
        regular_price: 45,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 45 }, start_date: "", end_date: "" },
        weight: "0.35",
        dimensions: { length: "40", width: "30", height: "4" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 3,
        stock_status: "lowstock",
        backorders: "no",
        reviews_allowed: true,
        upsells: ["prod2"],
        cross_sells: ["prod2", "prod3"],
        attributes: [
            { id: 2, name: "Size", options: ["XS", "S", "M", "L", "XL"], visible: true, variation: false },
            { id: 1, name: "Colour", options: ["Charcoal", "Black", "Slate Blue"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 14, name: "joggers", slug: "joggers" }, { id: 8, name: "casual", slug: "casual" }],
        visibility: "visible",
        date_published: "2024-09-25",
        created_at: "2024-09-25T10:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod9",
        sku: "DNJ-009",
        title: "Washed Denim Jacket",
        description: "Stone-washed denim jacket with a classic trucker silhouette. Button front, two chest pockets and side entry pockets.",
        short_description: "Classic stone-washed trucker denim jacket.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/denim_jacket", secure_url: IMG.denim_jacket },
        allow_back_orders: false,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 89 },
        regular_price: 110,
        sale_price: 89,
        on_sale: true,
        sale: { status: true, price: { currency: "GBP", amount: 89 }, start_date: "2024-10-01", end_date: "2025-02-28" },
        weight: "0.90",
        dimensions: { length: "40", width: "55", height: "5" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 17,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: ["prod3"],
        cross_sells: ["prod8", "prod10"],
        attributes: [
            { id: 2, name: "Size", options: ["S", "M", "L", "XL", "XXL"], visible: true, variation: false },
            { id: 1, name: "Wash", options: ["Light", "Mid", "Dark"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 15, name: "denim", slug: "denim" }, { id: 16, name: "jackets", slug: "jackets" }],
        visibility: "visible",
        date_published: "2024-10-01",
        created_at: "2024-10-01T08:00:00Z",
        featured: true,
        gallery: []
    },
    {
        _id: "prod10",
        sku: "PLO-010",
        title: "Piqué Polo Shirt",
        description: "Breathable cotton piqué polo with a three-button placket and ribbed collar. Ideal for smart-casual occasions.",
        short_description: "Cotton piqué polo, three-button placket.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/polo_shirt", secure_url: IMG.polo_shirt },
        allow_back_orders: false,
        low_stock_threshold: 8,
        sold_individually: false,
        price: { currency: "GBP", amount: 42 },
        regular_price: 42,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 42 }, start_date: "", end_date: "" },
        weight: "0.25",
        dimensions: { length: "30", width: "25", height: "3" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 65,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: ["prod2"],
        cross_sells: [],
        attributes: [
            { id: 2, name: "Size", options: ["S", "M", "L", "XL", "XXL"], visible: true, variation: false },
            { id: 1, name: "Colour", options: ["White", "Navy", "Burgundy", "Forest Green"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 17, name: "polo", slug: "polo" }, { id: 18, name: "smart-casual", slug: "smart-casual" }],
        visibility: "visible",
        date_published: "2024-10-15",
        created_at: "2024-10-15T09:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod11",
        sku: "WLT-011",
        title: "Slim Bifold Wallet",
        description: "Minimalist genuine leather bifold wallet with 6 card slots, a bill compartment and an RFID-blocking layer.",
        short_description: "Slim leather bifold wallet with RFID blocking.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/wallet", secure_url: IMG.wallet },
        allow_back_orders: false,
        low_stock_threshold: 10,
        sold_individually: false,
        price: { currency: "GBP", amount: 35 },
        regular_price: 35,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 35 }, start_date: "", end_date: "" },
        weight: "0.08",
        dimensions: { length: "10", width: "8", height: "1" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 110,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod5", "prod12"],
        attributes: [
            { id: 8, name: "Colour", options: ["Tan", "Black", "Dark Brown"], visible: true, variation: false }
        ],
        purchase_note: "Delivered in a gift-ready sleeve.",
        enable_reviews: true,
        categories: [{ id: 8, name: "Accessories", slug: "accessories" }],
        tags: [{ id: 10, name: "gifts", slug: "gifts" }, { id: 19, name: "wallets", slug: "wallets" }],
        visibility: "visible",
        date_published: "2024-11-01",
        created_at: "2024-11-01T08:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod12",
        sku: "BLT-012",
        title: "Woven Leather Belt",
        description: "Hand-stitched woven leather belt with a brushed silver buckle. Full-grain leather, built to last.",
        short_description: "Full-grain woven leather belt, silver buckle.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/belt", secure_url: IMG.belt },
        allow_back_orders: false,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 28 },
        regular_price: 28,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 28 }, start_date: "", end_date: "" },
        weight: "0.18",
        dimensions: { length: "100", width: "4", height: "0.5" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 74,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: [],
        cross_sells: ["prod8", "prod9", "prod11"],
        attributes: [
            { id: 9, name: "Size", options: ["S/M (28–32\")", "M/L (32–36\")", "L/XL (36–40\")"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 8, name: "Accessories", slug: "accessories" }],
        tags: [{ id: 20, name: "belts", slug: "belts" }],
        visibility: "visible",
        date_published: "2024-11-10",
        created_at: "2024-11-10T09:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod13",
        sku: "SCF-013",
        title: "Merino Wool Scarf",
        description: "Lightweight merino wool scarf in a generous 180 × 35 cm cut. Naturally temperature-regulating and itch-free.",
        short_description: "Lightweight merino wool scarf, 180 × 35 cm.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/scarf", secure_url: IMG.scarf },
        allow_back_orders: true,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 38 },
        regular_price: 48,
        sale_price: 38,
        on_sale: true,
        sale: { status: true, price: { currency: "GBP", amount: 38 }, start_date: "2024-12-01", end_date: "2025-02-28" },
        weight: "0.18",
        dimensions: { length: "180", width: "35", height: "0.5" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 0,
        stock_status: "outofstock",
        backorders: "notify",
        reviews_allowed: true,
        upsells: ["prod3"],
        cross_sells: ["prod9"],
        attributes: [
            { id: 1, name: "Colour", options: ["Camel", "Charcoal", "Burgundy", "Ivory"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 8, name: "Accessories", slug: "accessories" }],
        tags: [{ id: 21, name: "scarves", slug: "scarves" }, { id: 5, name: "knitwear", slug: "knitwear" }],
        visibility: "visible",
        date_published: "2024-12-01",
        created_at: "2024-12-01T08:00:00Z",
        featured: false,
        gallery: []
    },
    {
        _id: "prod14",
        sku: "BMB-014",
        title: "Satin Bomber Jacket",
        description: "Relaxed-fit satin bomber with ribbed collar, cuffs and hem. Lined interior with a hidden zip pocket.",
        short_description: "Relaxed satin bomber with ribbed trims.",
        type: "simple",
        status: "publish",
        variations: [],
        image: { public_id: "products/bomber", secure_url: IMG.bomber },
        allow_back_orders: false,
        low_stock_threshold: 4,
        sold_individually: false,
        price: { currency: "GBP", amount: 95 },
        regular_price: 95,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 95 }, start_date: "", end_date: "" },
        weight: "0.70",
        dimensions: { length: "65", width: "55", height: "5" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 29,
        stock_status: "instock",
        backorders: "no",
        reviews_allowed: true,
        upsells: ["prod9"],
        cross_sells: ["prod8", "prod4"],
        attributes: [
            { id: 2, name: "Size", options: ["XS", "S", "M", "L", "XL"], visible: true, variation: false },
            { id: 1, name: "Colour", options: ["Black", "Champagne", "Olive"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: true,
        categories: [{ id: 3, name: "Apparel", slug: "apparel" }],
        tags: [{ id: 16, name: "jackets", slug: "jackets" }, { id: 22, name: "bomber", slug: "bomber" }],
        visibility: "visible",
        date_published: "2025-01-05",
        created_at: "2025-01-05T09:00:00Z",
        featured: true,
        gallery: []
    },
    {
        _id: "prod15",
        sku: "DRS-015",
        title: "Wrap Midi Dress",
        description: "Floaty wrap midi dress in a lightweight woven fabric. V-neckline, adjustable tie waist and flutter sleeves.",
        short_description: "Lightweight wrap midi dress, flutter sleeves.",
        type: "simple",
        status: "draft",
        variations: [],
        image: { public_id: "products/dress", secure_url: IMG.dress },
        allow_back_orders: false,
        low_stock_threshold: 5,
        sold_individually: false,
        price: { currency: "GBP", amount: 68 },
        regular_price: 68,
        sale_price: null,
        on_sale: false,
        sale: { status: false, price: { currency: "GBP", amount: 68 }, start_date: "", end_date: "" },
        weight: "0.30",
        dimensions: { length: "110", width: "40", height: "2" },
        shipping_class: "standard",
        tax_status: "taxable",
        tax_class: "",
        manage_stock: true,
        stock_quantity: 0,
        stock_status: "outofstock",
        backorders: "no",
        reviews_allowed: false,
        upsells: [],
        cross_sells: [],
        attributes: [
            { id: 2, name: "Size", options: ["XS", "S", "M", "L", "XL"], visible: true, variation: false },
            { id: 1, name: "Colour", options: ["Sage Green", "Dusty Rose", "Cobalt Blue"], visible: true, variation: false }
        ],
        purchase_note: "",
        enable_reviews: false,
        categories: [{ id: 8, name: "Women's Apparel", slug: "womens-apparel" }],
        tags: [{ id: 23, name: "dresses", slug: "dresses" }, { id: 18, name: "smart-casual", slug: "smart-casual" }],
        visibility: "hidden",
        date_published: null,
        created_at: "2025-02-10T10:00:00Z",
        featured: false,
        gallery: []
    }
];
