export const coupons = [
    {
        created_by: { first_name: "Vladislaus", last_name: "Draguila" },
        code: "BBC_SEPT_10",
        description: "10% off for new seasonal collection (Jan-Jun)",
        allow_free_shipping: false,
        expiry_date: new Date("2023-06-30").getTime(),
        discount_type: "PERCENTAGE",
        coupon_amount: 10,
        type: "PERCENTAGE",
        start_date: new Date("2023-01-01").getTime(),
        status: "EXPIRED",
        minimum_spend: { amount: 50, currency: "GBP" },
        maximum_spend: { amount: 1000, currency: "GBP" },
        is_individual_use: true,
        exclude_sale_items: true,
        products: [],
        exclude_products: [],
        product_categories: ["apparel"],
        exclude_categories: [],
        allowed_emails: [],
        usage_limit_per_coupon: 100,
        usage_per_person: 1,
        limit_usage_to_x_items: 10,
        published: true
    },
    {
        created_by: { first_name: "Maria", last_name: "Gonzalez" },
        code: "SPRING15_2025",
        description: "15% off spring arrivals",
        allow_free_shipping: false,
        expiry_date: new Date("2025-05-31").getTime(),
        discount_type: "PERCENTAGE",
        coupon_amount: 15,
        type: "PERCENTAGE",
        start_date: new Date("2025-03-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 20, currency: "USD" },
        maximum_spend: { amount: 500, currency: "USD" },
        is_individual_use: true,
        exclude_sale_items: true,
        products: ["P101", "P102"],
        exclude_products: [],
        product_categories: ["spring", "women"],
        exclude_categories: [],
        allowed_emails: [],
        usage_limit_per_coupon: 200,
        usage_per_person: 1,
        limit_usage_to_x_items: 3,
        published: true
    },
    {
        created_by: { first_name: "James", last_name: "Morrison" },
        code: "FREESHIP50",
        description: "Free shipping for orders over 50 USD",
        allow_free_shipping: true,
        expiry_date: new Date("2026-01-01").getTime(),
        discount_type: "FREE_SHIPPING",
        coupon_amount: 0,
        type: "FREE_SHIPPING",
        start_date: new Date("2025-06-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 50, currency: "USD" },
        maximum_spend: null,
        is_individual_use: false,
        exclude_sale_items: false,
        products: [],
        exclude_products: [],
        product_categories: [],
        exclude_categories: [],
        allowed_emails: ["vip@domain.com"],
        usage_limit_per_coupon: 1000,
        usage_per_person: 2,
        limit_usage_to_x_items: 0,
        published: true
    },
    {
        created_by: { first_name: "Seth", last_name: "Mensah" },
        code: "GH_XMAS_30",
        description: "30% off Christmas promo (GHS)",
        allow_free_shipping: false,
        expiry_date: new Date("2025-12-26").getTime(),
        discount_type: "PERCENTAGE",
        coupon_amount: 30,
        type: "PERCENTAGE",
        start_date: new Date("2025-12-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 200, currency: "GHS" },
        maximum_spend: { amount: 3000, currency: "GHS" },
        is_individual_use: true,
        exclude_sale_items: true,
        products: ["GH202", "GH404"],
        exclude_products: ["GH999"],
        product_categories: ["electronics"],
        exclude_categories: ["clearance"],
        allowed_emails: [],
        usage_limit_per_coupon: 100,
        usage_per_person: 1,
        limit_usage_to_x_items: 2,
        published: true
    },
    {
        created_by: { first_name: "Aisha", last_name: "Kamara" },
        code: "WELCOME5",
        description: "Flat $5 off for first order",
        allow_free_shipping: false,
        expiry_date: new Date("2026-06-30").getTime(),
        discount_type: "FIXED",
        coupon_amount: 5,
        type: "FIXED",
        start_date: new Date("2024-01-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 10, currency: "USD" },
        maximum_spend: null,
        is_individual_use: true,
        exclude_sale_items: false,
        products: [],
        exclude_products: [],
        product_categories: [],
        exclude_categories: [],
        allowed_emails: [],
        usage_limit_per_coupon: 10000,
        usage_per_person: 1,
        limit_usage_to_x_items: 1,
        published: true
    },
    {
        created_by: { first_name: "Kenji", last_name: "Ito" },
        code: "JP_NEWYEAR_2026",
        description: "10% off New Year special (JPY)",
        allow_free_shipping: false,
        expiry_date: new Date("2026-01-10").getTime(),
        discount_type: "PERCENTAGE",
        coupon_amount: 10,
        type: "PERCENTAGE",
        start_date: new Date("2026-01-01").getTime(),
        status: "UPCOMING",
        minimum_spend: { amount: 3000, currency: "JPY" },
        maximum_spend: { amount: 200000, currency: "JPY" },
        is_individual_use: false,
        exclude_sale_items: false,
        products: ["JP1001"],
        exclude_products: [],
        product_categories: ["gifts"],
        exclude_categories: [],
        allowed_emails: [],
        usage_limit_per_coupon: 500,
        usage_per_person: 3,
        limit_usage_to_x_items: 0,
        published: false
    },
    {
        created_by: { first_name: "Lina", last_name: "Owusu" },
        code: "STUDENT25",
        description: "25% student discount (with verified email)",
        allow_free_shipping: true,
        expiry_date: new Date("2025-11-30").getTime(),
        discount_type: "PERCENTAGE",
        coupon_amount: 25,
        type: "PERCENTAGE",
        start_date: new Date("2025-09-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 0, currency: "USD" },
        maximum_spend: { amount: 300, currency: "USD" },
        is_individual_use: true,
        exclude_sale_items: true,
        products: [],
        exclude_products: [],
        product_categories: ["books", "stationery"],
        exclude_categories: [],
        allowed_emails: ["*.edu", "students@university.edu"],
        usage_limit_per_coupon: 1000,
        usage_per_person: 1,
        limit_usage_to_x_items: 5,
        published: true
    },
    {
        created_by: { first_name: "Omar", last_name: "El-Sayed" },
        code: "BUNDLE50",
        description: "50 off on bundle purchases over 500 EGP",
        allow_free_shipping: false,
        expiry_date: new Date("2025-10-01").getTime(),
        discount_type: "FIXED",
        coupon_amount: 50,
        type: "FIXED",
        start_date: new Date("2025-07-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 500, currency: "EGP" },
        maximum_spend: null,
        is_individual_use: false,
        exclude_sale_items: false,
        products: ["EGP200", "EGP201"],
        exclude_products: [],
        product_categories: ["bundles"],
        exclude_categories: [],
        allowed_emails: [],
        usage_limit_per_coupon: 300,
        usage_per_person: 2,
        limit_usage_to_x_items: 10,
        published: true
    },
    {
        created_by: { first_name: "Nora", last_name: "Peterson" },
        code: "BLACKFRI_2025",
        description: "Black Friday 2025 — 40% off sitewide",
        allow_free_shipping: true,
        expiry_date: new Date("2025-11-29").getTime(),
        discount_type: "PERCENTAGE",
        coupon_amount: 40,
        type: "PERCENTAGE",
        start_date: new Date("2025-11-28").getTime(),
        status: "UPCOMING",
        minimum_spend: { amount: 0, currency: "USD" },
        maximum_spend: null,
        is_individual_use: false,
        exclude_sale_items: true,
        products: [],
        exclude_products: [],
        product_categories: [],
        exclude_categories: [],
        allowed_emails: [],
        usage_limit_per_coupon: 100000,
        usage_per_person: 10,
        limit_usage_to_x_items: 0,
        published: false
    },
    {
        created_by: { first_name: "Paul", last_name: "Adjei" },
        code: "LOYALTY100",
        description: "Loyalty members: $100 off when you spend $1000",
        allow_free_shipping: false,
        expiry_date: new Date("2026-12-31").getTime(),
        discount_type: "FIXED",
        coupon_amount: 100,
        type: "FIXED",
        start_date: new Date("2025-01-01").getTime(),
        status: "ACTIVE",
        minimum_spend: { amount: 1000, currency: "USD" },
        maximum_spend: null,
        is_individual_use: true,
        exclude_sale_items: true,
        products: [],
        exclude_products: [],
        product_categories: [],
        exclude_categories: [],
        allowed_emails: ["loyal@brand.com"],
        usage_limit_per_coupon: 100,
        usage_per_person: 1,
        limit_usage_to_x_items: 0,
        published: true
    }
];
