export const coupons = [
    {
        _id: "cpn1",
        created_by: { first_name: "Vladislaus", last_name: "Draguila" },
        code: "BBC_SEPT_10",
        description: "10% off for new seasonal collection (Jan-Jun)",
        allow_free_shipping: false,
        date_expires: "2023-06-30",
        discount_type: "percent",
        amount: 10,
        start_date: "2023-01-01",
        status: "EXPIRED",
        minimum_spend: 50,
        maximum_spend: 1000,
        individual_use: true,
        exclude_sale_items: true,
        product_ids: [],
        excluded_product_ids: [],
        product_categories: [3],
        excluded_product_categories: [],
        included_emails: [],
        usage_limit: 100,
        usage_limit_per_user: 1,
        limit_usage_to_x_items: 10,
        usage_count: 87,
        created_at: "2023-01-01T00:00:00Z"
    },
    {
        _id: "cpn2",
        created_by: { first_name: "Maria", last_name: "Gonzalez" },
        code: "SPRING15_2025",
        description: "15% off spring arrivals",
        allow_free_shipping: false,
        date_expires: "2025-05-31",
        discount_type: "percent",
        amount: 15,
        start_date: "2025-03-01",
        status: "ACTIVE",
        minimum_spend: 20,
        maximum_spend: 500,
        individual_use: true,
        exclude_sale_items: true,
        product_ids: [101, 102],
        excluded_product_ids: [],
        product_categories: [5, 8],
        excluded_product_categories: [],
        included_emails: [],
        usage_limit: 200,
        usage_limit_per_user: 1,
        limit_usage_to_x_items: 3,
        usage_count: 34,
        created_at: "2025-03-01T00:00:00Z"
    },
    {
        _id: "cpn3",
        created_by: { first_name: "James", last_name: "Morrison" },
        code: "FREESHIP50",
        description: "Free shipping for orders over £50",
        allow_free_shipping: true,
        date_expires: "2026-01-01",
        discount_type: "shipping",
        amount: 0,
        start_date: "2025-06-01",
        status: "ACTIVE",
        minimum_spend: 50,
        maximum_spend: null,
        individual_use: false,
        exclude_sale_items: false,
        product_ids: [],
        excluded_product_ids: [],
        product_categories: [],
        excluded_product_categories: [],
        included_emails: ["vip@domain.com"],
        usage_limit: 1000,
        usage_limit_per_user: 2,
        limit_usage_to_x_items: 0,
        usage_count: 212,
        created_at: "2025-06-01T00:00:00Z"
    },
    {
        _id: "cpn4",
        created_by: { first_name: "Seth", last_name: "Mensah" },
        code: "GH_XMAS_30",
        description: "30% off Christmas promo",
        allow_free_shipping: false,
        date_expires: "2025-12-26",
        discount_type: "percent",
        amount: 30,
        start_date: "2025-12-01",
        status: "ACTIVE",
        minimum_spend: 200,
        maximum_spend: 3000,
        individual_use: true,
        exclude_sale_items: true,
        product_ids: [202, 404],
        excluded_product_ids: [999],
        product_categories: [12],
        excluded_product_categories: [7],
        included_emails: [],
        usage_limit: 100,
        usage_limit_per_user: 1,
        limit_usage_to_x_items: 2,
        usage_count: 0,
        created_at: "2025-11-15T00:00:00Z"
    },
    {
        _id: "cpn5",
        created_by: { first_name: "Aisha", last_name: "Kamara" },
        code: "WELCOME5",
        description: "Flat £5 off for first order",
        allow_free_shipping: false,
        date_expires: "2026-06-30",
        discount_type: "fixed_cart",
        amount: 5,
        start_date: "2024-01-01",
        status: "ACTIVE",
        minimum_spend: 10,
        maximum_spend: null,
        individual_use: true,
        exclude_sale_items: false,
        product_ids: [],
        excluded_product_ids: [],
        product_categories: [],
        excluded_product_categories: [],
        included_emails: [],
        usage_limit: 10000,
        usage_limit_per_user: 1,
        limit_usage_to_x_items: 1,
        usage_count: 4821,
        created_at: "2024-01-01T00:00:00Z"
    },
    {
        _id: "cpn6",
        created_by: { first_name: "Kenji", last_name: "Ito" },
        code: "JP_NEWYEAR_2026",
        description: "10% off New Year special",
        allow_free_shipping: false,
        date_expires: "2026-01-10",
        discount_type: "percent",
        amount: 10,
        start_date: "2026-01-01",
        status: "ACTIVE",
        minimum_spend: 30,
        maximum_spend: 2000,
        individual_use: false,
        exclude_sale_items: false,
        product_ids: [1001],
        excluded_product_ids: [],
        product_categories: [15],
        excluded_product_categories: [],
        included_emails: [],
        usage_limit: 500,
        usage_limit_per_user: 3,
        limit_usage_to_x_items: 0,
        usage_count: 9,
        created_at: "2025-12-20T00:00:00Z"
    },
    {
        _id: "cpn7",
        created_by: { first_name: "Lina", last_name: "Owusu" },
        code: "STUDENT25",
        description: "25% student discount (with verified email)",
        allow_free_shipping: true,
        date_expires: "2025-11-30",
        discount_type: "percent",
        amount: 25,
        start_date: "2025-09-01",
        status: "EXPIRED",
        minimum_spend: 0,
        maximum_spend: 300,
        individual_use: true,
        exclude_sale_items: true,
        product_ids: [],
        excluded_product_ids: [],
        product_categories: [9, 11],
        excluded_product_categories: [],
        included_emails: ["students@university.edu"],
        usage_limit: 1000,
        usage_limit_per_user: 1,
        limit_usage_to_x_items: 5,
        usage_count: 463,
        created_at: "2025-09-01T00:00:00Z"
    },
    {
        _id: "cpn8",
        created_by: { first_name: "Omar", last_name: "El-Sayed" },
        code: "BUNDLE50",
        description: "£50 off on bundle purchases over £500",
        allow_free_shipping: false,
        date_expires: "2025-10-01",
        discount_type: "fixed_cart",
        amount: 50,
        start_date: "2025-07-01",
        status: "EXPIRED",
        minimum_spend: 500,
        maximum_spend: null,
        individual_use: false,
        exclude_sale_items: false,
        product_ids: [200, 201],
        excluded_product_ids: [],
        product_categories: [6],
        excluded_product_categories: [],
        included_emails: [],
        usage_limit: 300,
        usage_limit_per_user: 2,
        limit_usage_to_x_items: 10,
        usage_count: 297,
        created_at: "2025-07-01T00:00:00Z"
    },
    {
        _id: "cpn9",
        created_by: { first_name: "Nora", last_name: "Peterson" },
        code: "BLACKFRI_2025",
        description: "Black Friday 2025 — 40% off sitewide",
        allow_free_shipping: true,
        date_expires: "2025-11-29",
        discount_type: "percent",
        amount: 40,
        start_date: "2025-11-28",
        status: "EXPIRED",
        minimum_spend: 0,
        maximum_spend: null,
        individual_use: false,
        exclude_sale_items: true,
        product_ids: [],
        excluded_product_ids: [],
        product_categories: [],
        excluded_product_categories: [],
        included_emails: [],
        usage_limit: 100000,
        usage_limit_per_user: 10,
        limit_usage_to_x_items: 0,
        usage_count: 18742,
        created_at: "2025-11-01T00:00:00Z"
    },
    {
        _id: "cpn10",
        created_by: { first_name: "Paul", last_name: "Adjei" },
        code: "LOYALTY100",
        description: "Loyalty members: £100 off when you spend £1000",
        allow_free_shipping: false,
        date_expires: "2026-12-31",
        discount_type: "fixed_cart",
        amount: 100,
        start_date: "2025-01-01",
        status: "ACTIVE",
        minimum_spend: 1000,
        maximum_spend: null,
        individual_use: true,
        exclude_sale_items: true,
        product_ids: [],
        excluded_product_ids: [],
        product_categories: [],
        excluded_product_categories: [],
        included_emails: ["loyal@brand.com"],
        usage_limit: 100,
        usage_limit_per_user: 1,
        limit_usage_to_x_items: 0,
        usage_count: 17,
        created_at: "2025-01-01T00:00:00Z"
    }
];
