export const testimonials = [
    {
        _id: "t1",
        name: "Ama Serwaa",
        avatar: "https://i.pravatar.cc/150?img=47",
        location: "Accra, GH",
        rating: 5,
        title: "Quality that surprised me",
        content: "The fabric is thick and soft. Wore it all day and it still held shape. Shipping was fast and the packaging felt premium.",
        product: "Classic Hoodie",
        status: "approved",
        is_verified: true,
        created_at: "2025-04-19T09:30:00Z"
    },
    {
        _id: "t2",
        name: "Kwesi Owusu",
        avatar: "https://i.pravatar.cc/150?img=22",
        location: "Kumasi, GH",
        rating: 4,
        title: "Dope designs",
        content: "Minimal, bold, and fits true to size. Would love to see more colorways in the next drop.",
        product: "Icon Tee",
        status: "approved",
        is_verified: true,
        created_at: "2025-03-12T12:00:00Z"
    },
    {
        _id: "t3",
        name: "Selina Boat",
        avatar: "https://i.pravatar.cc/150?img=32",
        location: "London, UK",
        rating: 5,
        title: "New favorite brand",
        content: "I've ordered twice now. Customer support was quick to swap my size. The loyalty points are a nice touch!",
        product: "Track Pants",
        status: "approved",
        is_verified: false,
        created_at: "2025-02-28T18:10:00Z"
    },
    {
        _id: "t4",
        name: "Bright Nana",
        avatar: "https://i.pravatar.cc/150?img=14",
        location: "Takoradi, GH",
        rating: 3.5,
        title: "Good but room to improve",
        content: "Love the look. My only gripe: courier delayed a day. Brand kept me updated though. Will buy again.",
        product: "Utility Jacket",
        status: "pending",
        is_verified: true,
        created_at: "2025-04-05T08:15:00Z"
    },
    {
        _id: "t5",
        name: "Zara Mensah",
        avatar: "https://i.pravatar.cc/150?img=68",
        location: "Johannesburg, ZA",
        rating: 4.5,
        title: "Comfort + style",
        content: "The hoodie is comfy without being bulky. Stitching is clean. Compliments every time I wear it.",
        product: "Classic Hoodie",
        status: "approved",
        is_verified: true,
        created_at: "2025-01-18T10:00:00Z"
    },
    {
        _id: "t6",
        name: "Mike Johnson",
        avatar: "https://i.pravatar.cc/150?img=5",
        location: "New York, US",
        rating: 5,
        title: "Exactly what I wanted",
        content: "True to photos. Breathable tee, perfect for layering. Appreciate the eco-friendly packaging!",
        product: "Icon Tee",
        status: "approved",
        is_verified: false,
        created_at: "2025-04-21T20:05:00Z"
    }
];
