export const posts = [
    {
        _id: "post1",
        title: "An Extraordinary WebGL Has Been Released By Great China Scientists",
        excerpt: "Back in 2019, Gucci brought video games to its app with a new section called Gucci Arcade, inspired by creative direction...",
        content: "Back in 2019, Gucci brought video games to its app with a new section called Gucci Arcade, inspired by creative direction. The intersection of fashion and technology continues to evolve in exciting ways. From virtual try-ons to AI-powered styling, the future of fashion retail is being shaped by innovation.",
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
        tag: "Technology",
        status: "published",
        featured: true,
        author: { name: "Mohammad Reza", avatar: "https://randomuser.me/api/portraits/men/32.jpg" },
        created_at: "2024-06-27T10:00:00Z",
        updated_at: "2024-06-27T10:00:00Z"
    },
    {
        _id: "post2",
        title: "Exploring the Role of AI in Fashion Forecasting",
        excerpt: "AI is transforming how brands predict fashion trends and understand consumer behavior through data.",
        content: "Artificial intelligence is transforming how brands predict fashion trends and understand consumer behavior through data. Machine learning models now analyze social media, runway shows, and purchasing patterns to forecast what will be popular next season. This technology is helping brands reduce waste and better serve their customers.",
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
        tag: "AI",
        status: "published",
        featured: true,
        author: { name: "Ella Grant", avatar: "https://randomuser.me/api/portraits/women/44.jpg" },
        created_at: "2024-07-10T14:00:00Z",
        updated_at: "2024-07-10T14:00:00Z"
    },
    {
        _id: "post3",
        title: "The Role Of AI In Blockchain & Crypto Investments",
        excerpt: "Artificial intelligence is revolutionizing blockchain analytics and trading strategies. Find out how AI-driven solutions work.",
        content: "Artificial intelligence is revolutionizing blockchain analytics and trading strategies. From pattern recognition to automated trading bots, AI is making cryptocurrency markets more accessible. This article explores the key AI technologies being used in the crypto space and what it means for investors.",
        image: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
        tag: "Technology",
        status: "published",
        featured: false,
        author: { name: "Johan Leo", avatar: "https://randomuser.me/api/portraits/men/65.jpg" },
        created_at: "2024-08-14T09:00:00Z",
        updated_at: "2024-08-14T09:00:00Z"
    },
    {
        _id: "post4",
        title: "Traditional Finance: Which One Is The Future?",
        excerpt: "From enhanced security protocols to new use cases, discover the key trends shaping the future of finance.",
        content: "The debate between traditional finance and decentralized alternatives continues to heat up. While banks offer stability and regulatory protection, DeFi platforms provide unprecedented access and transparency. This article explores both sides and what the future might hold.",
        image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9",
        tag: "Finance",
        status: "published",
        featured: false,
        author: { name: "Johan Leo", avatar: "https://randomuser.me/api/portraits/men/65.jpg" },
        created_at: "2024-08-14T11:00:00Z",
        updated_at: "2024-08-14T11:00:00Z"
    },
    {
        _id: "post5",
        title: "Stay Up Summer Collection 2024: Behind The Scenes",
        excerpt: "Get an exclusive look at how we designed and produced the Stay Up Summer 2024 collection.",
        content: "Our summer 2024 collection was months in the making. From the initial sketches to fabric sourcing and final production, every step was guided by our commitment to quality and sustainability. In this post, we take you behind the scenes to see how your favorite pieces came to life.",
        image: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
        tag: "Fashion",
        status: "draft",
        featured: false,
        author: { name: "Ama Serwaa", avatar: "https://randomuser.me/api/portraits/women/68.jpg" },
        created_at: "2024-09-01T08:00:00Z",
        updated_at: "2024-09-05T14:30:00Z"
    },
    {
        _id: "post6",
        title: "Sustainable Fashion: Our Commitment to the Environment",
        excerpt: "Learn about Stay Up's sustainability initiatives and how we're reducing our environmental footprint.",
        content: "Sustainability isn't just a buzzword at Stay Up—it's a core value. From eco-friendly packaging to ethically sourced materials, we're committed to reducing our environmental impact. This article details our current initiatives and future goals for a greener fashion industry.",
        image: "https://images.unsplash.com/photo-1591696205602-2f950c417cb9",
        tag: "Sustainability",
        status: "published",
        featured: false,
        author: { name: "Kwame Asante", avatar: "https://randomuser.me/api/portraits/men/45.jpg" },
        created_at: "2024-09-15T10:00:00Z",
        updated_at: "2024-09-15T10:00:00Z"
    }
];
