// src/data/categories.seed.js
export const categories = [
    {
        _id: "cat_001",
        name: "Electronics",
        slug: "electronics",
        description: "All electronic devices and accessories — phones, laptops, audio, and more.",
        parent: null,
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2024-01-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Electronics – Shop", seo_description: "Top electronics at great prices" },
        product_count: 1243,
        created_at: new Date("2024-01-01T08:00:00.000Z").toISOString(),
        updated_at: new Date("2024-09-15T10:30:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/electronics.jpg", alt: "Electronics category" },
        created_by: { _id: "admin_01", first_name: "Vladislaus", last_name: "Draguila", email: "vlad@example.com" }
    },
    {
        _id: "cat_002",
        name: "Mobile Phones",
        slug: "mobile-phones",
        description: "Smartphones, feature phones and mobile accessories.",
        parent: "cat_001",
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2024-02-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Mobile Phones", seo_description: "Latest smartphones and deals" },
        product_count: 482,
        created_at: new Date("2024-02-01T09:00:00.000Z").toISOString(),
        updated_at: new Date("2024-10-01T12:00:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/mobile-phones.jpg", alt: "Smartphones and accessories" },
        created_by: { _id: "admin_02", first_name: "Maria", last_name: "Gonzalez", email: "maria@example.com" }
    },
    {
        _id: "cat_003",
        name: "Laptops & Computers",
        slug: "laptops-computers",
        description: "Laptops, desktops, monitors and computer accessories.",
        parent: "cat_001",
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2024-01-15T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Laptops & Computers", seo_description: "Performance laptops and desktops" },
        product_count: 312,
        created_at: new Date("2024-01-15T10:00:00.000Z").toISOString(),
        updated_at: new Date("2024-10-05T11:20:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/laptops.jpg", alt: "Laptops and computers" },
        created_by: { _id: "admin_01", first_name: "Vladislaus", last_name: "Draguila", email: "vlad@example.com" }
    },
    {
        _id: "cat_004",
        name: "Audio & Headphones",
        slug: "audio-headphones",
        description: "Headphones, earphones, speakers, microphones and audio accessories.",
        parent: "cat_001",
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2024-03-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Audio & Headphones", seo_description: "Quality sound equipment" },
        product_count: 198,
        created_at: new Date("2024-03-01T08:15:00.000Z").toISOString(),
        updated_at: new Date("2024-09-20T09:45:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/audio.jpg", alt: "Speakers and headphones" },
        created_by: { _id: "admin_03", first_name: "James", last_name: "Morrison", email: "james@example.com" }
    },
    {
        _id: "cat_005",
        name: "Home & Kitchen",
        slug: "home-kitchen",
        description: "Home appliances, kitchenware and home improvement items.",
        parent: null,
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2023-11-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Home & Kitchen", seo_description: "Make your house a home" },
        product_count: 856,
        created_at: new Date("2023-11-01T07:30:00.000Z").toISOString(),
        updated_at: new Date("2024-08-01T14:00:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/home-kitchen.jpg", alt: "Home and kitchen" },
        created_by: { _id: "admin_04", first_name: "Aisha", last_name: "Kamara", email: "aisha@example.com" }
    },
    {
        _id: "cat_006",
        name: "Kitchen Appliances",
        slug: "kitchen-appliances",
        description: "Cookers, blenders, kettles, and other kitchen appliances.",
        parent: "cat_005",
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2023-12-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Kitchen Appliances", seo_description: "Reliable kitchen gadgets" },
        product_count: 210,
        created_at: new Date("2023-12-01T09:00:00.000Z").toISOString(),
        updated_at: new Date("2024-07-10T08:00:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/kitchen-appliances.jpg", alt: "Kitchen appliances" },
        created_by: { _id: "admin_04", first_name: "Aisha", last_name: "Kamara", email: "aisha@example.com" }
    },
    {
        _id: "cat_007",
        name: "Fashion — Men",
        slug: "fashion-men",
        description: "Men's clothing, shoes and accessories.",
        parent: null,
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2024-04-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Men's Fashion", seo_description: "Latest trends for men" },
        product_count: 640,
        created_at: new Date("2024-04-01T06:00:00.000Z").toISOString(),
        updated_at: new Date("2024-10-10T09:00:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/fashion-men.jpg", alt: "Men's fashion" },
        created_by: { _id: "admin_05", first_name: "Paul", last_name: "Adjei", email: "paul@example.com" }
    },
    {
        _id: "cat_008",
        name: "Fashion — Women",
        slug: "fashion-women",
        description: "Women's clothing, shoes and accessories.",
        parent: null,
        published: true,
        status: "ACTIVE",
        visible_from: new Date("2024-04-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Women's Fashion", seo_description: "Stylish picks for women" },
        product_count: 780,
        created_at: new Date("2024-04-01T06:30:00.000Z").toISOString(),
        updated_at: new Date("2024-10-12T10:00:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/fashion-women.jpg", alt: "Women's fashion" },
        created_by: { _id: "admin_05", first_name: "Paul", last_name: "Adjei", email: "paul@example.com" }
    },
    {
        _id: "cat_009",
        name: "Clearance",
        slug: "clearance",
        description: "Clearance and closeout items — limited stock and deeply discounted.",
        parent: null,
        published: false,
        status: "PENDING",
        visible_from: new Date("2024-11-01T00:00:00.000Z").toISOString(),
        meta: { seo_title: "Clearance Deals", seo_description: "Snap up bargains while they last" },
        product_count: 96,
        created_at: new Date("2024-10-01T08:00:00.000Z").toISOString(),
        updated_at: new Date("2024-10-10T08:30:00.000Z").toISOString(),
        is_deleted: false,
        image: { url: "https://cdn.example.com/images/categories/clearance.jpg", alt: "Clearance deals" },
        created_by: { _id: "admin_06", first_name: "Lina", last_name: "Owusu", email: "lina@example.com" }
    },
    {
        _id: "cat_010",
        name: "Discontinued",
        slug: "discontinued",
        description: "Products no longer supported or removed from catalogue.",
        parent: null,
        published: false,
        status: "DELETED",
        visible_from: null,
        meta: { note: "Soft-deleted category for archival purposes" },
        product_count: 0,
        created_at: new Date("2022-06-01T09:00:00.000Z").toISOString(),
        updated_at: new Date("2023-01-15T10:00:00.000Z").toISOString(),
        is_deleted: true,
        image: { url: "https://cdn.example.com/images/categories/discontinued.jpg", alt: "Discontinued" },
        created_by: { _id: "admin_07", first_name: "Nora", last_name: "Peterson", email: "nora@example.com" }
    }
];
