export const taxRates = [
    {
        _id: "tr1",
        country: "US",
        state: "CA",
        postcode: "90001",
        city: "Los Angeles",
        rate: "9.5000",
        name: "CA State Tax",
        priority: 1,
        compound: false,
        shipping: true,
        tax_class: "standard",
        created_at: "2023-01-15T08:00:00Z"
    },
    {
        _id: "tr2",
        country: "GB",
        state: "",
        postcode: "",
        city: "",
        rate: "20.0000",
        name: "UK VAT Standard",
        priority: 1,
        compound: false,
        shipping: true,
        tax_class: "standard",
        created_at: "2023-02-01T09:00:00Z"
    },
    {
        _id: "tr3",
        country: "GB",
        state: "",
        postcode: "",
        city: "",
        rate: "5.0000",
        name: "UK VAT Reduced",
        priority: 1,
        compound: false,
        shipping: false,
        tax_class: "reduced-rate",
        created_at: "2023-02-01T09:05:00Z"
    },
    {
        _id: "tr4",
        country: "NG",
        state: "LA",
        postcode: "",
        city: "Lagos",
        rate: "7.5000",
        name: "Nigeria VAT",
        priority: 1,
        compound: false,
        shipping: false,
        tax_class: "standard",
        created_at: "2023-03-10T10:00:00Z"
    },
    {
        _id: "tr5",
        country: "CA",
        state: "ON",
        postcode: "",
        city: "",
        rate: "13.0000",
        name: "Ontario HST",
        priority: 1,
        compound: true,
        shipping: true,
        tax_class: "standard",
        created_at: "2023-04-05T11:00:00Z"
    }
];
