const BLACK_BRIDGE_CLOTHING_ADMIN_THEME = 'BLACK_BRIDGE_CLOTHING_ADMIN_THEME';
const BLACK_BRIDGE_CLOTHING_ADMIN_VIEW = 'BLACK_BRIDGE_CLOTHING_ADMIN_VIEW';
const BLACK_BRIDGE_CLOTHING_ADMIN_SIDEBAR_EXPANDED = 'BLACK_BRIDGE_CLOTHING_ADMIN_SIDEBAR_EXPANDED';

export const BLACK_BRIDGE_CLOTHING_ADMIN_CONSTANTS = {
    BLACK_BRIDGE_CLOTHING_ADMIN_THEME,
    BLACK_BRIDGE_CLOTHING_ADMIN_VIEW,
    BLACK_BRIDGE_CLOTHING_ADMIN_SIDEBAR_EXPANDED
};