const STAY_UP_ADMIN_THEME = 'STAY_UP_ADMIN_THEME';
const STAY_UP_ADMIN_VIEW = 'STAY_UP_ADMIN_VIEW';
const STAY_UP_ADMIN_SIDEBAR_EXPANDED = 'STAY_UP_ADMIN_SIDEBAR_EXPANDED';
const STAY_UP_ADMIN_API_BASE = "http://localhost:4000/api";

export const STAY_UP_ADMIN_CONSTANTS = {
    STAY_UP_ADMIN_THEME,
    STAY_UP_ADMIN_VIEW,
    STAY_UP_ADMIN_SIDEBAR_EXPANDED,
    STAY_UP_ADMIN_API_BASE
};